/**
 * Booking domain rules shared by the appointments API.
 *
 * Prices are derived HERE from the service duration — never trusted from the
 * client. Conflict checking queries a window wide enough to catch bookings
 * that started earlier (including the previous day) but overlap the requested
 * slot. Writes run under a Serializable transaction (see
 * runSerializableBooking) so two concurrent overlap checks cannot both pass.
 */

import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";

/** Service price (EUR) by appointment duration in minutes. Must mirror the
 *  services offered in BookClient.tsx. */
export const SERVICE_PRICES: Record<number, number> = {
    30: 25,
    60: 50,
};

export const ALLOWED_DURATIONS = Object.keys(SERVICE_PRICES).map(Number);

const MAX_DURATION_MINUTES = 120;

/** Clinic hours are local to the practice, NOT to the server (Vercel runs in
 *  UTC) or to the patient's browser. */
export const CLINIC_TIMEZONE = "Europe/Sofia";
export const CLINIC_OPEN_HOUR = 9; // first slot starts 09:00
export const CLINIC_CLOSE_HOUR = 17; // last slot starts 16:30

function clinicHourMinute(date: Date): { hour: number; minute: number } {
    const parts = new Intl.DateTimeFormat("en-GB", {
        timeZone: CLINIC_TIMEZONE,
        hour: "2-digit",
        minute: "2-digit",
        hour12: false,
    }).formatToParts(date);
    const get = (type: string) => Number(parts.find((p) => p.type === type)?.value ?? NaN);
    // Intl yields "24" for midnight with hour12: false in some ICU versions
    const hour = get("hour") % 24;
    return { hour, minute: get("minute") };
}

/**
 * A bookable slot starts on a half-hour boundary between 09:00 and 16:30
 * clinic time. Mirrors the slot grid generated by BookClient.tsx.
 */
export function isWithinBusinessHours(start: Date): boolean {
    if (start.getUTCSeconds() !== 0 || start.getUTCMilliseconds() !== 0) return false;
    const { hour, minute } = clinicHourMinute(start);
    if (minute !== 0 && minute !== 30) return false;
    return hour >= CLINIC_OPEN_HOUR && hour < CLINIC_CLOSE_HOUR;
}

interface BookedSlot {
    dateTime: Date;
    duration: number;
}

/** Pure overlap test: [startA, endA) intersects [startB, endB). */
export function overlaps(start: Date, durationMin: number, other: BookedSlot): boolean {
    const startMs = start.getTime();
    const endMs = startMs + durationMin * 60_000;
    const otherStart = other.dateTime.getTime();
    const otherEnd = otherStart + other.duration * 60_000;
    return startMs < otherEnd && endMs > otherStart;
}

/**
 * Returns true if an active (BOOKED) appointment overlaps the requested slot.
 * The query window starts MAX_DURATION_MINUTES before the slot so bookings
 * that began earlier — including on the previous day — are still considered.
 */
export async function hasConflict(
    tx: Prisma.TransactionClient,
    start: Date,
    durationMin: number,
    excludeId?: string
): Promise<boolean> {
    const windowStart = new Date(start.getTime() - MAX_DURATION_MINUTES * 60_000);
    const windowEnd = new Date(start.getTime() + durationMin * 60_000);

    const candidates = await tx.appointment.findMany({
        where: {
            status: "BOOKED",
            dateTime: { gte: windowStart, lt: windowEnd },
            ...(excludeId ? { id: { not: excludeId } } : {}),
        },
        select: { dateTime: true, duration: true },
    });

    return candidates.some((appt) => overlaps(start, durationMin, appt));
}

/**
 * Run a booking write under Serializable isolation, retrying once when
 * Postgres aborts the transaction due to a concurrent conflicting write
 * (Prisma error P2034). Callers should map a P2034 that escapes this helper
 * to a 409 response.
 */
export async function runSerializableBooking<T>(
    fn: (tx: Prisma.TransactionClient) => Promise<T>
): Promise<T> {
    try {
        return await prisma.$transaction(fn, {
            isolationLevel: Prisma.TransactionIsolationLevel.Serializable,
        });
    } catch (err) {
        if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2034") {
            return await prisma.$transaction(fn, {
                isolationLevel: Prisma.TransactionIsolationLevel.Serializable,
            });
        }
        throw err;
    }
}

/** True when the error is a write conflict the API should report as 409. */
export function isBookingConflictError(err: unknown): boolean {
    return (
        err instanceof Prisma.PrismaClientKnownRequestError &&
        (err.code === "P2034" || err.code === "P2002")
    );
}
